export const message = {
  FILE_REQUIRED: "File is required",
  FILE_SIZE: "Image size must be less than 2MB",
  FILE_TYPE: "Image size should be jpg or png only",
  NAME_REQUIRED: "Name is required",
  NAME_ALPHABATE: "Pleae enter alphabate only",
  NAME_MIN_LENGHT: "Name is too short!",
  NAME_MAX_LENGHT: "Name is too long!",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_INVALID: "Email is invalid",
  PHONE_REQUIRED: "Phone number must be required",
  PHONE_INVALID: "Phone number is invalid",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_LENGHT: "Password must be least 8 charaters",
  CONFIRMPASSWORD_REQUIRED: "Confirm Password is required",
  CONFIRMPASSWORD_MATCHED: "Passwords must be match",
};
